Repository cpp-park-vk-education/2023_1_Japanese_gardens_and_landscapes, pull requests merged in 2023-05, with the labels that each got.

#13 Dev: [ADEF-BBS-011] Graphics: Renderer: base implementation with Sprite-component support
  libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
  libs/AnimeDefendersEngine/include/SpriteComponent/Sprite.hpp
  libs/AnimeDefendersEngine/src/CameraComponent/Camera.cpp
  libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
  libs/AnimeDefendersEngine/src/SpriteComponent/Sprite.cpp
Labels: Task, develop

#22 Dev: [ADEF-BBS-015] Graphics: Sprite: System and components definision
  libs/AnimeDefendersEngine/include/SpriteComponent/Sprite.hpp
  libs/AnimeDefendersEngine/include/SpriteComponent/SpriteSystem.hpp
  libs/AnimeDefendersEngine/src/SpriteComponent/Sprite.cpp
  libs/AnimeDefendersEngine/src/SpriteComponent/SpriteSystem.cpp
Labels: Task, develop

#23 Dev: [ADEF-BBS-016] Graphics: Camera: System and components definision
  libs/AnimeDefendersEngine/include/SpriteComponent/Sprite.hpp
  libs/AnimeDefendersEngine/include/SpriteComponent/SpriteSystem.hpp
  libs/AnimeDefendersEngine/src/SpriteComponent/Sprite.cpp
  libs/AnimeDefendersEngine/src/SpriteComponent/SpriteSystem.cpp
Labels: Task, develop

#17 [ADEF-BBS-002] Tools: implement class for easy tables reading from stream
  libs/AnimeDefendersEngine/CMakeLists.txt
  libs/AnimeDefendersEngine/include/FileSystem/TableReader.hpp
  libs/AnimeDefendersEngine/src/FileSystem/TableReader.cpp
  libs/AnimeDefendersEngine/src/Physics/BodyDefinition.cpp
Labels: Task

#25 [ADEF-BBS-013] Graphics: OpenGl dependency: IDrawTextureWrapper imlp
  libs/AnimeDefendersEngine/include/Graphics/Color.hpp
  libs/AnimeDefendersEngine/include/Graphics/IDrawTextureWrapper.hpp
  libs/AnimeDefendersEngine/include/Graphics/Texture.hpp
  libs/AnimeDefendersEngine/include/OpenGlDependency/DrawTextureWrapper.hpp
  libs/AnimeDefendersEngine/src/OpenGlDependency/DrawTextureWrapper.cpp
Labels: Task

#27 [ADEF-BBS-024] Graphics: OpenGL dependency: IWindow implementation
  libs/AnimeDefendersEngine/include/Graphics/IWindow.hpp
  libs/AnimeDefendersEngine/include/OpenGlDependency/Window.hpp
  libs/AnimeDefendersEngine/src/OpenGlDependency/Window.cpp
Labels: Task

#12 [ADEF-BBS-034] Core: Game Loop: GameLoop impl
  libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
  libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
  libs/AnimeDefendersEngine/include/Systems/ISystemManager.hpp
  libs/AnimeDefendersEngine/include/Systems/SystemManager.hpp
  libs/AnimeDefendersEngine/src/AnimeFramework/EventManager.cpp
  libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
  libs/AnimeDefendersEngine/src/Systems/SystemManager.cpp
Labels: Task

#36 [ADEF-BBS-004] Physics: Physics System implementation
  libs/AnimeDefendersEngine/CMakeLists.txt
  libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
  libs/AnimeDefendersEngine/include/Physics/PhysicsSystem.hpp
  libs/AnimeDefendersEngine/include/Physics/RigidBodyComponent.hpp
  libs/AnimeDefendersEngine/include/Physics/TransformComponent.hpp
  libs/AnimeDefendersEngine/src/Physics/ColliderComponent.cpp
  libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
  libs/AnimeDefendersEngine/src/Physics/PhysicsWorld.cpp
Labels: Task

#11 [ADEF-BBS-045] Math: Vector2: Implemented Vector2 operators and functions
  libs/AnimeDefendersEngine/CMakeLists.txt
  libs/AnimeDefendersEngine/include/Math/Vector2.hpp
  libs/AnimeDefendersEngine/src/Math/Vector2.cpp
Labels: Task

#28 [ADEF-BBS-016] Graphics: Camera: System and components definition
  libs/AnimeDefendersEngine/include/CameraComponent/Camera.hpp
  libs/AnimeDefendersEngine/include/CameraComponent/CameraSystem.hpp
  libs/AnimeDefendersEngine/src/CameraComponent/Camera.cpp
  libs/AnimeDefendersEngine/src/CameraComponent/CameraSystem.cpp
  tests/CMakeLists.txt
Labels: Task

#38 [ADEF-BBS-FIX] Fixed Vector2 not compiling with Physics
  libs/AnimeDefendersEngine/CMakeLists.txt
  libs/AnimeDefendersEngine/include/Math/Vector2.hpp
  libs/AnimeDefendersEngine/src/Math/Vector2.cpp
  libs/AnimeDefendersEngine/src/Physics/Manifold.cpp
Labels: bug

#39 [ADEF-BBS-FIX] Added missing changes
  libs/AnimeDefendersEngine/src/Physics/PhysicsWorld.cpp
Labels: bug

#8 [ADEF-BBS-011] Graphics: Renderer: base implementation with Sprite-component support
  libs/AnimeDefendersEngine/include/Graphics/Renderer.hpp
  libs/AnimeDefendersEngine/src/Graphics/Renderer.cpp
Labels: Task

#40 [ADEF-BBS-051] Physics: fixing bugs
  libs/AnimeDefendersEngine/CMakeLists.txt
  libs/AnimeDefendersEngine/include/Physics/ColliderComponent.hpp
  libs/AnimeDefendersEngine/include/Physics/PhysicsSystem.hpp
  libs/AnimeDefendersEngine/include/Physics/PhysicsWorld.hpp
  libs/AnimeDefendersEngine/include/Physics/TransformComponent.hpp
  libs/AnimeDefendersEngine/src/Physics/ColliderComponent.cpp
  libs/AnimeDefendersEngine/src/Physics/CollisionHandler.cpp
  libs/AnimeDefendersEngine/src/Physics/PhysicsSystem.cpp
Labels: Task

#19 [ADEF-BBS-043] Event System: Implement EventManager, Event, EventListener and InputManager
  libs/AnimeDefendersEngine/CMakeLists.txt
  libs/AnimeDefendersEngine/include/AnimeFramework/Event.hpp
  libs/AnimeDefendersEngine/include/AnimeFramework/EventListener.hpp
  libs/AnimeDefendersEngine/include/AnimeFramework/EventManager.hpp
  libs/AnimeDefendersEngine/include/AnimeFramework/GameLoop.hpp
  libs/AnimeDefendersEngine/include/AnimeFramework/InputManager.hpp
  libs/AnimeDefendersEngine/src/AnimeFramework/EventListener.cpp
  libs/AnimeDefendersEngine/src/AnimeFramework/EventManager.cpp
  libs/AnimeDefendersEngine/src/AnimeFramework/GameLoop.cpp
  libs/AnimeDefendersEngine/src/AnimeFramework/InputManager.cpp
Labels: Task
